// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: nf6.proto

package nf6

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type None struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *None) Reset() {
	*x = None{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *None) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*None) ProtoMessage() {}

func (x *None) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use None.ProtoReflect.Descriptor instead.
func (*None) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{0}
}

type CreateAccount_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SshPubKey string `protobuf:"bytes,2,opt,name=sshPubKey,proto3" json:"sshPubKey,omitempty"`
	TlsPubKey string `protobuf:"bytes,3,opt,name=tlsPubKey,proto3" json:"tlsPubKey,omitempty"`
}

func (x *CreateAccount_Request) Reset() {
	*x = CreateAccount_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount_Request) ProtoMessage() {}

func (x *CreateAccount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount_Request.ProtoReflect.Descriptor instead.
func (*CreateAccount_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccount_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccount_Request) GetSshPubKey() string {
	if x != nil {
		return x.SshPubKey
	}
	return ""
}

func (x *CreateAccount_Request) GetTlsPubKey() string {
	if x != nil {
		return x.TlsPubKey
	}
	return ""
}

type CreateAccount_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert string `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *CreateAccount_Reply) Reset() {
	*x = CreateAccount_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccount_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount_Reply) ProtoMessage() {}

func (x *CreateAccount_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount_Reply.ProtoReflect.Descriptor instead.
func (*CreateAccount_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccount_Reply) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

type GetCaCert_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaCert string `protobuf:"bytes,1,opt,name=caCert,proto3" json:"caCert,omitempty"`
}

func (x *GetCaCert_Reply) Reset() {
	*x = GetCaCert_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaCert_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaCert_Reply) ProtoMessage() {}

func (x *GetCaCert_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaCert_Reply.ProtoReflect.Descriptor instead.
func (*GetCaCert_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{3}
}

func (x *GetCaCert_Reply) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

type GetAccount_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	SshPubKey string `protobuf:"bytes,3,opt,name=sshPubKey,proto3" json:"sshPubKey,omitempty"`
	TlsPubKey string `protobuf:"bytes,4,opt,name=tlsPubKey,proto3" json:"tlsPubKey,omitempty"`
}

func (x *GetAccount_Reply) Reset() {
	*x = GetAccount_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccount_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccount_Reply) ProtoMessage() {}

func (x *GetAccount_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccount_Reply.ProtoReflect.Descriptor instead.
func (*GetAccount_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccount_Reply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAccount_Reply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAccount_Reply) GetSshPubKey() string {
	if x != nil {
		return x.SshPubKey
	}
	return ""
}

func (x *GetAccount_Reply) GetTlsPubKey() string {
	if x != nil {
		return x.TlsPubKey
	}
	return ""
}

type UpdateAccount_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SshPubKey string `protobuf:"bytes,2,opt,name=sshPubKey,proto3" json:"sshPubKey,omitempty"`
	TlsPubKey string `protobuf:"bytes,3,opt,name=tlsPubKey,proto3" json:"tlsPubKey,omitempty"`
}

func (x *UpdateAccount_Request) Reset() {
	*x = UpdateAccount_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAccount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccount_Request) ProtoMessage() {}

func (x *UpdateAccount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccount_Request.ProtoReflect.Descriptor instead.
func (*UpdateAccount_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccount_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateAccount_Request) GetSshPubKey() string {
	if x != nil {
		return x.SshPubKey
	}
	return ""
}

func (x *UpdateAccount_Request) GetTlsPubKey() string {
	if x != nil {
		return x.TlsPubKey
	}
	return ""
}

type CreateHost_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr6    string `protobuf:"bytes,2,opt,name=addr6,proto3" json:"addr6,omitempty"`
	WgPubKey string `protobuf:"bytes,3,opt,name=wgPubKey,proto3" json:"wgPubKey,omitempty"`
}

func (x *CreateHost_Request) Reset() {
	*x = CreateHost_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateHost_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHost_Request) ProtoMessage() {}

func (x *CreateHost_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHost_Request.ProtoReflect.Descriptor instead.
func (*CreateHost_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{6}
}

func (x *CreateHost_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHost_Request) GetAddr6() string {
	if x != nil {
		return x.Addr6
	}
	return ""
}

func (x *CreateHost_Request) GetWgPubKey() string {
	if x != nil {
		return x.WgPubKey
	}
	return ""
}

type GetHost_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetHost_Request) Reset() {
	*x = GetHost_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHost_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHost_Request) ProtoMessage() {}

func (x *GetHost_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHost_Request.ProtoReflect.Descriptor instead.
func (*GetHost_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{7}
}

func (x *GetHost_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetHost_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addr6    string `protobuf:"bytes,3,opt,name=addr6,proto3" json:"addr6,omitempty"`
	WgPubKey string `protobuf:"bytes,4,opt,name=wgPubKey,proto3" json:"wgPubKey,omitempty"`
}

func (x *GetHost_Reply) Reset() {
	*x = GetHost_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHost_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHost_Reply) ProtoMessage() {}

func (x *GetHost_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHost_Reply.ProtoReflect.Descriptor instead.
func (*GetHost_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{8}
}

func (x *GetHost_Reply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetHost_Reply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHost_Reply) GetAddr6() string {
	if x != nil {
		return x.Addr6
	}
	return ""
}

func (x *GetHost_Reply) GetWgPubKey() string {
	if x != nil {
		return x.WgPubKey
	}
	return ""
}

type ListHosts_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *ListHosts_Reply) Reset() {
	*x = ListHosts_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHosts_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHosts_Reply) ProtoMessage() {}

func (x *ListHosts_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHosts_Reply.ProtoReflect.Descriptor instead.
func (*ListHosts_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{9}
}

func (x *ListHosts_Reply) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type UpdateHost_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addr6    string `protobuf:"bytes,3,opt,name=addr6,proto3" json:"addr6,omitempty"`
	WgPubKey string `protobuf:"bytes,4,opt,name=wgPubKey,proto3" json:"wgPubKey,omitempty"`
}

func (x *UpdateHost_Request) Reset() {
	*x = UpdateHost_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateHost_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHost_Request) ProtoMessage() {}

func (x *UpdateHost_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHost_Request.ProtoReflect.Descriptor instead.
func (*UpdateHost_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateHost_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHost_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateHost_Request) GetAddr6() string {
	if x != nil {
		return x.Addr6
	}
	return ""
}

func (x *UpdateHost_Request) GetWgPubKey() string {
	if x != nil {
		return x.WgPubKey
	}
	return ""
}

type CreateRepo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateRepo_Request) Reset() {
	*x = CreateRepo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRepo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRepo_Request) ProtoMessage() {}

func (x *CreateRepo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRepo_Request.ProtoReflect.Descriptor instead.
func (*CreateRepo_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRepo_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRepo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRepo_Request) Reset() {
	*x = GetRepo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepo_Request) ProtoMessage() {}

func (x *GetRepo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepo_Request.ProtoReflect.Descriptor instead.
func (*GetRepo_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{12}
}

func (x *GetRepo_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRepo_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRepo_Reply) Reset() {
	*x = GetRepo_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepo_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepo_Reply) ProtoMessage() {}

func (x *GetRepo_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepo_Reply.ProtoReflect.Descriptor instead.
func (*GetRepo_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{13}
}

func (x *GetRepo_Reply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRepo_Reply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRepos_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *ListRepos_Reply) Reset() {
	*x = ListRepos_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRepos_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepos_Reply) ProtoMessage() {}

func (x *ListRepos_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepos_Reply.ProtoReflect.Descriptor instead.
func (*ListRepos_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{14}
}

func (x *ListRepos_Reply) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type UpdateRepo_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateRepo_Request) Reset() {
	*x = UpdateRepo_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRepo_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepo_Request) ProtoMessage() {}

func (x *UpdateRepo_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepo_Request.ProtoReflect.Descriptor instead.
func (*UpdateRepo_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRepo_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRepo_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GitServer_GetAccount_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SshPubKey string `protobuf:"bytes,1,opt,name=sshPubKey,proto3" json:"sshPubKey,omitempty"`
}

func (x *GitServer_GetAccount_Request) Reset() {
	*x = GitServer_GetAccount_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitServer_GetAccount_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitServer_GetAccount_Request) ProtoMessage() {}

func (x *GitServer_GetAccount_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitServer_GetAccount_Request.ProtoReflect.Descriptor instead.
func (*GitServer_GetAccount_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{16}
}

func (x *GitServer_GetAccount_Request) GetSshPubKey() string {
	if x != nil {
		return x.SshPubKey
	}
	return ""
}

type GitServer_GetAccount_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *GitServer_GetAccount_Reply) Reset() {
	*x = GitServer_GetAccount_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitServer_GetAccount_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitServer_GetAccount_Reply) ProtoMessage() {}

func (x *GitServer_GetAccount_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitServer_GetAccount_Reply.ProtoReflect.Descriptor instead.
func (*GitServer_GetAccount_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{17}
}

func (x *GitServer_GetAccount_Reply) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GitServer_ListRepos_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *GitServer_ListRepos_Request) Reset() {
	*x = GitServer_ListRepos_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitServer_ListRepos_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitServer_ListRepos_Request) ProtoMessage() {}

func (x *GitServer_ListRepos_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitServer_ListRepos_Request.ProtoReflect.Descriptor instead.
func (*GitServer_ListRepos_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{18}
}

func (x *GitServer_ListRepos_Request) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GitServer_ListRepos_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *GitServer_ListRepos_Reply) Reset() {
	*x = GitServer_ListRepos_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GitServer_ListRepos_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitServer_ListRepos_Reply) ProtoMessage() {}

func (x *GitServer_ListRepos_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitServer_ListRepos_Reply.ProtoReflect.Descriptor instead.
func (*GitServer_ListRepos_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{19}
}

func (x *GitServer_ListRepos_Reply) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type WgServer_ListHosts_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []*WgServer_ListHosts_Reply_Host `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
}

func (x *WgServer_ListHosts_Reply) Reset() {
	*x = WgServer_ListHosts_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WgServer_ListHosts_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WgServer_ListHosts_Reply) ProtoMessage() {}

func (x *WgServer_ListHosts_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WgServer_ListHosts_Reply.ProtoReflect.Descriptor instead.
func (*WgServer_ListHosts_Reply) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{20}
}

func (x *WgServer_ListHosts_Reply) GetHosts() []*WgServer_ListHosts_Reply_Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type CreateRoute_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr6    string `protobuf:"bytes,1,opt,name=addr6,proto3" json:"addr6,omitempty"`
	WgPubKey string `protobuf:"bytes,2,opt,name=wgPubKey,proto3" json:"wgPubKey,omitempty"`
}

func (x *CreateRoute_Request) Reset() {
	*x = CreateRoute_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoute_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoute_Request) ProtoMessage() {}

func (x *CreateRoute_Request) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoute_Request.ProtoReflect.Descriptor instead.
func (*CreateRoute_Request) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{21}
}

func (x *CreateRoute_Request) GetAddr6() string {
	if x != nil {
		return x.Addr6
	}
	return ""
}

func (x *CreateRoute_Request) GetWgPubKey() string {
	if x != nil {
		return x.WgPubKey
	}
	return ""
}

type WgServer_ListHosts_Reply_Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr6    string `protobuf:"bytes,1,opt,name=addr6,proto3" json:"addr6,omitempty"`
	WgPubKey string `protobuf:"bytes,2,opt,name=wgPubKey,proto3" json:"wgPubKey,omitempty"`
}

func (x *WgServer_ListHosts_Reply_Host) Reset() {
	*x = WgServer_ListHosts_Reply_Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nf6_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WgServer_ListHosts_Reply_Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WgServer_ListHosts_Reply_Host) ProtoMessage() {}

func (x *WgServer_ListHosts_Reply_Host) ProtoReflect() protoreflect.Message {
	mi := &file_nf6_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WgServer_ListHosts_Reply_Host.ProtoReflect.Descriptor instead.
func (*WgServer_ListHosts_Reply_Host) Descriptor() ([]byte, []int) {
	return file_nf6_proto_rawDescGZIP(), []int{20, 0}
}

func (x *WgServer_ListHosts_Reply_Host) GetAddr6() string {
	if x != nil {
		return x.Addr6
	}
	return ""
}

func (x *WgServer_ListHosts_Reply_Host) GetWgPubKey() string {
	if x != nil {
		return x.WgPubKey
	}
	return ""
}

var File_nf6_proto protoreflect.FileDescriptor

var file_nf6_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6e, 0x66, 0x36, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6e, 0x66, 0x36,
	0x22, 0x06, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x69, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x73, 0x68, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x73, 0x68, 0x50,
	0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6c, 0x73, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6c, 0x73, 0x50, 0x75, 0x62,
	0x4b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x22, 0x29,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x43, 0x65, 0x72, 0x74, 0x5f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74, 0x22, 0x74, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x73, 0x68, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x73, 0x68, 0x50, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6c, 0x73, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6c, 0x73, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22,
	0x69, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x73, 0x68, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x73, 0x68, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x6c, 0x73, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6c, 0x73, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x5a, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x67,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x67,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73,
	0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x65, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x67, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x67, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x73, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x6a, 0x0a,
	0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36, 0x12, 0x1a, 0x0a,
	0x08, 0x77, 0x67, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x77, 0x67, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x5f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x27, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x5f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x38, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x1c, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x73, 0x68, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x73, 0x68, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79,
	0x22, 0x32, 0x0a, 0x1a, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x1b, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x31, 0x0a, 0x19, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x18, 0x57, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x38, 0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x57, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x1a, 0x38, 0x0a, 0x04, 0x48,
	0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x36, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x67, 0x50,
	0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x67, 0x50,
	0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x47, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x64, 0x64, 0x72, 0x36, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64,
	0x72, 0x36, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x67, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x67, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x32, 0x84,
	0x01, 0x0a, 0x09, 0x4e, 0x66, 0x36, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x47, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x2e,
	0x6e, 0x66, 0x36, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x66, 0x36, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x43, 0x61, 0x43, 0x65,
	0x72, 0x74, 0x12, 0x09, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x14, 0x2e,
	0x6e, 0x66, 0x36, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x43, 0x65, 0x72, 0x74, 0x5f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x8a, 0x06, 0x0a, 0x03, 0x4e, 0x66, 0x36, 0x12, 0x30, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x09, 0x2e, 0x6e, 0x66,
	0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x15, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1a, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x6e,
	0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x09, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12,
	0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74,
	0x73, 0x12, 0x09, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x14, 0x2e, 0x6e,
	0x66, 0x36, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x17, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48,
	0x6f, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x6e, 0x66,
	0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x17, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x09, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x12, 0x14, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x6e, 0x66, 0x36, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x5f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73,
	0x12, 0x09, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x14, 0x2e, 0x6e, 0x66,
	0x36, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x5f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70,
	0x6f, 0x12, 0x17, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6f, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x6e, 0x66, 0x36,
	0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x14, 0x47, 0x69, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x21, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x13, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x12, 0x20, 0x2e, 0x6e,
	0x66, 0x36, 0x2e, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x47, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x12, 0x57, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x4c, 0x69, 0x73,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x09, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e,
	0x65, 0x1a, 0x1d, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x57, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x32, 0x3d, 0x0a, 0x05, 0x4e, 0x66, 0x36, 0x57, 0x67, 0x12, 0x34, 0x0a, 0x0b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x6e, 0x66, 0x36,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x6e, 0x66, 0x36, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22,
	0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x64, 0x61, 0x6e, 0x65, 0x2f, 0x6e, 0x66, 0x36,
	0x2f, 0x6e, 0x66, 0x36, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nf6_proto_rawDescOnce sync.Once
	file_nf6_proto_rawDescData = file_nf6_proto_rawDesc
)

func file_nf6_proto_rawDescGZIP() []byte {
	file_nf6_proto_rawDescOnce.Do(func() {
		file_nf6_proto_rawDescData = protoimpl.X.CompressGZIP(file_nf6_proto_rawDescData)
	})
	return file_nf6_proto_rawDescData
}

var file_nf6_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_nf6_proto_goTypes = []interface{}{
	(*None)(nil),                          // 0: nf6.None
	(*CreateAccount_Request)(nil),         // 1: nf6.CreateAccount_Request
	(*CreateAccount_Reply)(nil),           // 2: nf6.CreateAccount_Reply
	(*GetCaCert_Reply)(nil),               // 3: nf6.GetCaCert_Reply
	(*GetAccount_Reply)(nil),              // 4: nf6.GetAccount_Reply
	(*UpdateAccount_Request)(nil),         // 5: nf6.UpdateAccount_Request
	(*CreateHost_Request)(nil),            // 6: nf6.CreateHost_Request
	(*GetHost_Request)(nil),               // 7: nf6.GetHost_Request
	(*GetHost_Reply)(nil),                 // 8: nf6.GetHost_Reply
	(*ListHosts_Reply)(nil),               // 9: nf6.ListHosts_Reply
	(*UpdateHost_Request)(nil),            // 10: nf6.UpdateHost_Request
	(*CreateRepo_Request)(nil),            // 11: nf6.CreateRepo_Request
	(*GetRepo_Request)(nil),               // 12: nf6.GetRepo_Request
	(*GetRepo_Reply)(nil),                 // 13: nf6.GetRepo_Reply
	(*ListRepos_Reply)(nil),               // 14: nf6.ListRepos_Reply
	(*UpdateRepo_Request)(nil),            // 15: nf6.UpdateRepo_Request
	(*GitServer_GetAccount_Request)(nil),  // 16: nf6.GitServer_GetAccount_Request
	(*GitServer_GetAccount_Reply)(nil),    // 17: nf6.GitServer_GetAccount_Reply
	(*GitServer_ListRepos_Request)(nil),   // 18: nf6.GitServer_ListRepos_Request
	(*GitServer_ListRepos_Reply)(nil),     // 19: nf6.GitServer_ListRepos_Reply
	(*WgServer_ListHosts_Reply)(nil),      // 20: nf6.WgServer_ListHosts_Reply
	(*CreateRoute_Request)(nil),           // 21: nf6.CreateRoute_Request
	(*WgServer_ListHosts_Reply_Host)(nil), // 22: nf6.WgServer_ListHosts_Reply.Host
}
var file_nf6_proto_depIdxs = []int32{
	22, // 0: nf6.WgServer_ListHosts_Reply.hosts:type_name -> nf6.WgServer_ListHosts_Reply.Host
	1,  // 1: nf6.Nf6Public.CreateAccount:input_type -> nf6.CreateAccount_Request
	0,  // 2: nf6.Nf6Public.GetCaCert:input_type -> nf6.None
	0,  // 3: nf6.Nf6.GetAccount:input_type -> nf6.None
	5,  // 4: nf6.Nf6.UpdateAccount:input_type -> nf6.UpdateAccount_Request
	6,  // 5: nf6.Nf6.CreateHost:input_type -> nf6.CreateHost_Request
	7,  // 6: nf6.Nf6.GetHost:input_type -> nf6.GetHost_Request
	0,  // 7: nf6.Nf6.ListHosts:input_type -> nf6.None
	10, // 8: nf6.Nf6.UpdateHost:input_type -> nf6.UpdateHost_Request
	11, // 9: nf6.Nf6.CreateRepo:input_type -> nf6.CreateRepo_Request
	12, // 10: nf6.Nf6.GetRepo:input_type -> nf6.GetRepo_Request
	0,  // 11: nf6.Nf6.ListRepos:input_type -> nf6.None
	15, // 12: nf6.Nf6.UpdateRepo:input_type -> nf6.UpdateRepo_Request
	16, // 13: nf6.Nf6.GitServer_GetAccount:input_type -> nf6.GitServer_GetAccount_Request
	18, // 14: nf6.Nf6.GitServer_ListRepos:input_type -> nf6.GitServer_ListRepos_Request
	0,  // 15: nf6.Nf6.WgServer_ListHosts:input_type -> nf6.None
	21, // 16: nf6.Nf6Wg.CreateRoute:input_type -> nf6.CreateRoute_Request
	2,  // 17: nf6.Nf6Public.CreateAccount:output_type -> nf6.CreateAccount_Reply
	3,  // 18: nf6.Nf6Public.GetCaCert:output_type -> nf6.GetCaCert_Reply
	4,  // 19: nf6.Nf6.GetAccount:output_type -> nf6.GetAccount_Reply
	0,  // 20: nf6.Nf6.UpdateAccount:output_type -> nf6.None
	0,  // 21: nf6.Nf6.CreateHost:output_type -> nf6.None
	8,  // 22: nf6.Nf6.GetHost:output_type -> nf6.GetHost_Reply
	9,  // 23: nf6.Nf6.ListHosts:output_type -> nf6.ListHosts_Reply
	0,  // 24: nf6.Nf6.UpdateHost:output_type -> nf6.None
	0,  // 25: nf6.Nf6.CreateRepo:output_type -> nf6.None
	13, // 26: nf6.Nf6.GetRepo:output_type -> nf6.GetRepo_Reply
	14, // 27: nf6.Nf6.ListRepos:output_type -> nf6.ListRepos_Reply
	0,  // 28: nf6.Nf6.UpdateRepo:output_type -> nf6.None
	17, // 29: nf6.Nf6.GitServer_GetAccount:output_type -> nf6.GitServer_GetAccount_Reply
	19, // 30: nf6.Nf6.GitServer_ListRepos:output_type -> nf6.GitServer_ListRepos_Reply
	20, // 31: nf6.Nf6.WgServer_ListHosts:output_type -> nf6.WgServer_ListHosts_Reply
	0,  // 32: nf6.Nf6Wg.CreateRoute:output_type -> nf6.None
	17, // [17:33] is the sub-list for method output_type
	1,  // [1:17] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_nf6_proto_init() }
func file_nf6_proto_init() {
	if File_nf6_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nf6_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*None); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccount_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccount_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaCert_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccount_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAccount_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateHost_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHost_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHost_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHosts_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateHost_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRepo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepo_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRepos_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRepo_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitServer_GetAccount_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitServer_GetAccount_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitServer_ListRepos_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GitServer_ListRepos_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WgServer_ListHosts_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoute_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nf6_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WgServer_ListHosts_Reply_Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nf6_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_nf6_proto_goTypes,
		DependencyIndexes: file_nf6_proto_depIdxs,
		MessageInfos:      file_nf6_proto_msgTypes,
	}.Build()
	File_nf6_proto = out.File
	file_nf6_proto_rawDesc = nil
	file_nf6_proto_goTypes = nil
	file_nf6_proto_depIdxs = nil
}
