// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: nf6.proto

package nf6

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Nf6_GetMachine_FullMethodName    = "/nf6.Nf6/GetMachine"
	Nf6_GetRepo_FullMethodName       = "/nf6.Nf6/GetRepo"
	Nf6_RebuildSystem_FullMethodName = "/nf6.Nf6/RebuildSystem"
)

// Nf6Client is the client API for Nf6 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Nf6Client interface {
	GetMachine(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineReply, error)
	GetRepo(ctx context.Context, in *GetRepoRequest, opts ...grpc.CallOption) (*GetRepoReply, error)
	RebuildSystem(ctx context.Context, in *RebuildSystemRequest, opts ...grpc.CallOption) (*RebuildSystemReply, error)
}

type nf6Client struct {
	cc grpc.ClientConnInterface
}

func NewNf6Client(cc grpc.ClientConnInterface) Nf6Client {
	return &nf6Client{cc}
}

func (c *nf6Client) GetMachine(ctx context.Context, in *GetMachineRequest, opts ...grpc.CallOption) (*GetMachineReply, error) {
	out := new(GetMachineReply)
	err := c.cc.Invoke(ctx, Nf6_GetMachine_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nf6Client) GetRepo(ctx context.Context, in *GetRepoRequest, opts ...grpc.CallOption) (*GetRepoReply, error) {
	out := new(GetRepoReply)
	err := c.cc.Invoke(ctx, Nf6_GetRepo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nf6Client) RebuildSystem(ctx context.Context, in *RebuildSystemRequest, opts ...grpc.CallOption) (*RebuildSystemReply, error) {
	out := new(RebuildSystemReply)
	err := c.cc.Invoke(ctx, Nf6_RebuildSystem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Nf6Server is the server API for Nf6 service.
// All implementations must embed UnimplementedNf6Server
// for forward compatibility
type Nf6Server interface {
	GetMachine(context.Context, *GetMachineRequest) (*GetMachineReply, error)
	GetRepo(context.Context, *GetRepoRequest) (*GetRepoReply, error)
	RebuildSystem(context.Context, *RebuildSystemRequest) (*RebuildSystemReply, error)
	mustEmbedUnimplementedNf6Server()
}

// UnimplementedNf6Server must be embedded to have forward compatible implementations.
type UnimplementedNf6Server struct {
}

func (UnimplementedNf6Server) GetMachine(context.Context, *GetMachineRequest) (*GetMachineReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMachine not implemented")
}
func (UnimplementedNf6Server) GetRepo(context.Context, *GetRepoRequest) (*GetRepoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepo not implemented")
}
func (UnimplementedNf6Server) RebuildSystem(context.Context, *RebuildSystemRequest) (*RebuildSystemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildSystem not implemented")
}
func (UnimplementedNf6Server) mustEmbedUnimplementedNf6Server() {}

// UnsafeNf6Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Nf6Server will
// result in compilation errors.
type UnsafeNf6Server interface {
	mustEmbedUnimplementedNf6Server()
}

func RegisterNf6Server(s grpc.ServiceRegistrar, srv Nf6Server) {
	s.RegisterService(&Nf6_ServiceDesc, srv)
}

func _Nf6_GetMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMachineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Nf6Server).GetMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nf6_GetMachine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Nf6Server).GetMachine(ctx, req.(*GetMachineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nf6_GetRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Nf6Server).GetRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nf6_GetRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Nf6Server).GetRepo(ctx, req.(*GetRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nf6_RebuildSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Nf6Server).RebuildSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nf6_RebuildSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Nf6Server).RebuildSystem(ctx, req.(*RebuildSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nf6_ServiceDesc is the grpc.ServiceDesc for Nf6 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nf6_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nf6.Nf6",
	HandlerType: (*Nf6Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMachine",
			Handler:    _Nf6_GetMachine_Handler,
		},
		{
			MethodName: "GetRepo",
			Handler:    _Nf6_GetRepo_Handler,
		},
		{
			MethodName: "RebuildSystem",
			Handler:    _Nf6_RebuildSystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nf6.proto",
}
